module.exports = {
	rules: {
		'attr-case': 'error',
		'attr-quotes': 'error',
		'attribute-allowed-values': 'error',
		'attribute-boolean-style': 'error',
		'button-type': 'error',
		'close-attr': 'error',
		'close-order': 'error',
		'deprecated': 'error',
		'element-case': 'error',
		'element-name': 'error',
		'element-permitted-content': 'error',
		'element-permitted-occurrences': 'error',
		'element-permitted-order': 'error',
		'img-req-alt': 'error',
		'no-conditional-comment': 'error',
		'no-deprecated-attr': 'error',
		'no-dup-attr': 'error',
		'no-dup-class': 'error',
		'no-dup-id': 'error',
		'no-implicit-close': 'error',
		'no-inline-style': 'error',
		'no-trailing-whitespace': 'error',
		'void': 'error',
	},
};
