#!/bin/sh

# bail out on first error
set -e

echo Build sources
npm run build
grunt dgeni

echo Run unittests
npm test

echo Run linting
npm run eslint -- --max-warnings 0
npm run tslint

echo Lint documentation
./bin/html-validate.js docs/**/*.html public/**/.html
