#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# bail out on first error
set -e

echo Build sources
npm run build
npm run build:docs

echo Run unittests
npm test

echo Run linting
npm run eslint -- --max-warnings 0
npm run prettier:check

echo Lint documentation
npm run htmlvalidate -- --config docs/htmlvalidate-templates.json 'docs/**/*.html'
npm run htmlvalidate -- --config docs/htmlvalidate-public.json 'public/**/*.html'
