#!/bin/sh

if [ $# -lt 4 ]; then
	echo 'usage: trigger-downstream ID TOKEN BRANCH VERSION'
	exit 1
fi

hostname="$1"
id="$2"
token="$3"
branch="$4"
version="$5"

exec curl --silent --show-error --fail \
	 --stderr /dev/stderr \
	 --output /dev/null \
	 -X POST \
	 -F "token=${token}" \
	 -F "ref=${branch}" \
	 -F "variables[UPSTREAM_VERSION]=${version}" \
	 https://${hostname}/api/v4/projects/${id}/trigger/pipeline
